### ISSUE TITLE
Request for IP Range banning to be implemented

### ISSUE THREAD

**Issue by NormanDunbar** [splitbrain/dokuwiki-plugin-ipban#22]
Greetings.

_If I could write code in PHP, I would. But, sadly, I can't._

I have a persistent spammer who signs up as a human, bypasses all the bot checks and so on, then creates spam pages. When I delete the user and pages, s/he signs up again and repeats the offence.

Unfortunately, his IP address range is in the 196.0.0.0/8 range, which is quite a lot to ban individually. 

Is it at all possible to have something like '192.0.0.0/8' set as the IP address to ban, and have it ban anyone form that range of IP addresses? It would make my life easier.

Thanks for the work done so far, it is much appreciated.

Cheers,
Norm.

**Comment by NormanDunbar** [comment]
Good Evening @splitbrain ,

I notice you have closed this request. I wonder if you would mind explaining why please? It's not a duplicate, as far as I can tell, for example. Thanks.

Cheers,
Norm.

**Comment by splitbrain** [comment]
see the referenced commit. it's implemented

**Comment by NormanDunbar** [comment]
Morning @splitbrain,

thank you very much. Apologies - I didn't see the commit link on your closure notice. I'm getting old. :(

Once again, thanks for the hard work.


Cheers,
Norm.
